name: Odding
favicon: null
layout_spectrum: 0.15764657175168395
typography_spectrum: 0.23323205299675465
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.19093106407672167
  lightness: 0.3151461281813681
  saturation: 0.022596100578084588
  rhythmicContrast: 0.25833728816360235
purpose: []
